import java.util.Scanner; // program uses class Scanner



public class Division 

{

   public static void main(String[] args)

   {

      Scanner input = new Scanner(System.in);



      int number1; 

      int number2; 

      int div; 



      System.out.print("Enter first integer: "); 

      number1 = input.nextInt(); 



      System.out.print("Enter second integer: "); 

      number2 = input.nextInt(); 



      vid = number1 / number2; 



      System.out.printf("Div is %d%n", div); 



   } 

} 